site_name: GOODFOOD API DOC
site_url: "http://localhost:8000"
dev_addr: "localhost:8000"

nav:
  - Accueil: index.md
  - Services: 
    - Conteneurs: services/services.md
    - Installation: services/install.md
    - Configuration: services/conf.md
    - Modes: app/application.md
    - Mise à jour: services/update.md
    - OSM: services/osm.md
  - Base de données:
    - Fonctionnelle: databases/core.md
    - Authentification: databases/auth.md
    - Versions: databases/versions.md
  - Développement:
    - API: debug/postman.md
    - Débuggage: debug/telescope.md
  - Sécurité: 
    - Authentification: security/security.md
    - Permissions: security/permissions.md
  - Fichiers: files/file.md
  - Test:
    - PHPUnit: test/phpunit.md
  - API: redoc/redoc-static.html
  - Namespaces: doctum/index.html

theme:
  name: material
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: teal
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: red
      accent: red
  icon:
    logo: material/noodles


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences