name: "Build"

on: 
  push:
    branches:
      - main
      - develop
      - feature/*
      - release/*
    pull_request:
      - develop
      - main
      - types: [opened, synchronize, reopened]


jobs:
  build:
    name: "Build Docker Image And push to Docker Hub"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Disabling shallow clone is recommended for improving relevancy of reporting

      - name: Build the docker image
        run: docker build . --file Dockerfile --tag goodfoodcesi2022/api:latest --build-arg user=www --build-arg uid=1000 --rm
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push to Docker Hub
        run: docker push goodfoodcesi2022/api:latest

  test:
    name: "Test PHPUnit"
    needs: build
    runs-on: ubuntu-latest
    container:
      image: goodfoodcesi2022/api:latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
        # Run in custom image with phpfpm
      - name: Prepare Laravel Application
        run: |
          cd /var/www
          ls -la
          cp .env.ci .env
          php artisan key:generate
          
      - name: Run tests
        run: |
          cd /var/www
          php artisan test --coverage-xml 

      - name: Fix code coverage paths for Sonar phpunit.coverage.xml
        run: |
          cd /var/www
          sed -i 's/\/home\/runner\/work\/GoodFood-Cesi-2022\/GOOD-FOOD-2.0P\//\/github\/workspace\//g' phpunit.coverage.xml

      - name: Upload PHPUnit Artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          path: /var/www/phpunit.coverage.xml

  quality:
    name: Quality Job with SonarCloud
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Disabling shallow clone is recommended for improving relevancy of reporting

      - name: Download PHPUnit Coverage to be analyse by sonar
        uses: actions/download-artifact@v3.0.0
        with:
          name: phpunit.coverage.xml
          path: ./phpunit.coverage.xml

      - name : SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      



        